Global:
  model_name: PP-OCRv4_mobile_rec
  debug: false
  use_gpu: false
  epoch_num: 200
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: e:/Phuc's Data/Github/Cham-OCR/data/output/rec_cham
  save_epoch_step: 10
  eval_batch_step:
  - 0
  - 1000
  cal_metric_during_train: true
  pretrained_model: e:/Phuc's Data/Github/Cham-OCR/data/pretrain_models/ch_PP-OCRv4_rec_train/best_accuracy
  checkpoints: null
  save_inference_dir: null
  use_visualdl: false
  infer_img: doc/imgs_words/ch/word_1.jpg
  character_dict_path: e:/Phuc's Data/Github/Cham-OCR/data/cham_dict.txt
  max_text_length: 80
  infer_mode: false
  use_space_char: true
  distributed: true
  save_res_path: e:/Phuc's Data/Github/Cham-OCR/data/output/rec_cham
  d2s_train_image_shape:
  - 3
  - 48
  - 1024
Optimizer:
  name: Adam
  beta1: 0.9
  beta2: 0.999
  lr:
    name: Cosine
    learning_rate: 0.001
    warmup_epoch: 5
  regularizer:
    name: L2
    factor: 3.0e-05
Architecture:
  model_type: rec
  algorithm: SVTR_LCNet
  Transform: null
  Backbone:
    name: PPLCNetV3
    scale: 0.95
  Head:
    name: MultiHead
    head_list:
    - CTCHead:
        Neck:
          name: svtr
          dims: 120
          depth: 2
          hidden_dims: 120
          kernel_size:
          - 1
          - 3
          use_guide: true
        Head:
          fc_decay: 1.0e-05
    - NRTRHead:
        nrtr_dim: 384
        max_text_length: 80
Loss:
  name: MultiLoss
  loss_config_list:
  - CTCLoss: null
  - NRTRLoss: null
PostProcess:
  name: CTCLabelDecode
Metric:
  name: RecMetric
  main_indicator: acc
Train:
  dataset:
    name: MultiScaleDataSet
    ds_width: false
    data_dir: e:/Phuc's Data/Github/Cham-OCR/data/cham_synthetic_images
    ext_op_transform_idx: 1
    label_file_list:
    - e:/Phuc's Data/Github/Cham-OCR/data/cham_synthetic_images/train_label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - RecConAug:
        prob: 0.5
        ext_data_num: 2
        image_shape:
        - 48
        - 1024
        - 3
        max_text_length: 80
    - RecAug: null
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  sampler:
    name: MultiScaleSampler
    scales:
    - - 1024
      - 32
    - - 1024
      - 48
    - - 1024
      - 64
    first_bs: 64
    fix_bs: false
    divided_factor:
    - 8
    - 16
    is_training: true
  loader:
    shuffle: true
    batch_size_per_card: 64
    drop_last: true
    num_workers: 2
Eval:
  dataset:
    name: SimpleDataSet
    data_dir: e:/Phuc's Data/Github/Cham-OCR/data/cham_synthetic_images
    label_file_list:
    - e:/Phuc's Data/Github/Cham-OCR/data/cham_synthetic_images/val_clean_short_label.txt
    transforms:
    - DecodeImage:
        img_mode: BGR
        channel_first: false
    - MultiLabelEncode:
        gtc_encode: NRTRLabelEncode
    - RecResizeImg:
        image_shape:
        - 3
        - 48
        - 1024
    - KeepKeys:
        keep_keys:
        - image
        - label_ctc
        - label_gtc
        - length
        - valid_ratio
  loader:
    shuffle: false
    drop_last: false
    batch_size_per_card: 64
    num_workers: 2
